### ISSUE TITLE
`git_commit_all()`: handle is not a git_sig_ptr

### ISSUE THREAD

**Issue by pat-s** [r-lib/gert#7] opened 2019-07-08 08:59 UTC
```r
git_commit_all("fix DESC")
Error in git_commit(message = message, author = author, committer = committer,  : 
  handle is not a git_sig_ptr
```

file gets staged but not commited.

Arch, libgit 0.28.2

**Comment by jeroen** [comment] 2019-07-15 22:40
Hmm is this the master branch? I can't reproduce this issue.

**Comment by jeroen** [comment] 2019-07-15 22:41
I think this was already fixed by https://github.com/r-lib/gert/commit/2fc5b776ba2c510e15f8e49c868bd4bc58e706c4. Let me know if you still see this in the master branch!

**Closed as completed by jeroen** 2019-07-15 22:41 UTC
